-- 1. Table des profils utilisateurs
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    last_name TEXT,
    first_name TEXT,
    email TEXT,
    password TEXT,
    role TEXT DEFAULT 'client',
    address TEXT,
    phone NUMERIC,
    PRIMARY KEY (id)
);

-- 2. Table des produits
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price FLOAT8 NOT NULL,
    description TEXT,
    category TEXT,
    stock_quantity FLOAT8 DEFAULT 0,
    image_url VARCHAR,
    PRIMARY KEY (id)
);

-- 3. Table des commandes
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    log_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    total FLOAT8 NOT NULL,
    tax NUMERIC DEFAULT 0,
    order_date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'pending',
    delivery_address TEXT,
    payment_method TEXT,
    PRIMARY KEY (id)
);

-- 4. Table des articles de commande (Liaison Commandes <-> Produits)
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
    prod_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    quantity BIGINT NOT NULL,
    price FLOAT8 NOT NULL,
    PRIMARY KEY (id)
);

-- 5. Table des rendez-vous
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    log_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    date DATE NOT NULL,
    time TIME WITHOUT TIME ZONE NOT NULL,
    status TEXT DEFAULT 'pending',
    note TEXT,
    PRIMARY KEY (id)
);

-- 6. Table des transactions
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type TEXT,
    amount FLOAT8 NOT NULL,
    date DATE DEFAULT CURRENT_DATE,
    status TEXT DEFAULT 'pending',
    comment TEXT,
    PRIMARY KEY (id)
);