server {
    listen 443 ssl;  
    server_name kine-web.be www.kine-web.be m1-4.ephec-ti.be;
    include /etc/nginx/mime.types;
    
    ssl_certificate     /etc/nginx/ssl/live/m1-4.ephec-ti.be-0001/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/m1-4.ephec-ti.be-0001/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        root /usr/share/nginx/html;
        include /etc/nginx/mime.types;
    }

    location /api/ {
        proxy_pass http://backend:3000; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}